host:
  baidu_api: http://www.baidu.com

db:
  starling_read:
    host: localhost
    port: 3306
    username: root
    password:
    database: flytear_starling
  starling_write:
    host: localhost
    port: 3306
    username: root
    password:
    database: flytear_starling

redis: